### PR TITLE
Verify dependencies

### PR DESCRIPTION
**Pull request by rochoa**
This adds a grunt task to validate shared dependencies with cartodb.js.

In order to keep dependencies synced between two projects this will make test task to fail if dependencies mismatch.

Having dependencies in sync is important to not have different ones bundled into the final dist files. This reduces the size of bundles.

### CODE REVIEW

**Comment by rochoa** [comment]
cc @viddo

**Comment by rochoa** [comment]
Not sure if I should add some kind of test for this.

**Comment by viddo** [comment]
:+1: Let's give this a try

**Comment by rochoa** [comment]
I'm merging it. I hope this in combination with https://github.com/CartoDB/deep-insights.js/pull/32 will help to keep shared dependencies under control.

**Pull request merged**
