### PR TITLE
time-series: draggable histogram and click

### PR DESCRIPTION
**Pull request by matallo**
re: https://github.com/CartoDB/cartodb/issues/12180

tests pending

### CODE REVIEW

**Comment by matallo** [comment]
just pushed the first tests, not really sure what's the best approach though

**Comment by xavijam** [comment]
Hey, do we have any PR in CartoDB pointing to these changes?

**Comment by xavijam** [comment]
And, if you don't mind @rjimenezda, could you resolve the conflicts? 🙏

**Comment by rjimenezda** [comment]
Hey, nope, sorry, I'll create a branch as soon as I fix the conflicts

**Comment by xavijam** [comment]
I've just created one don't worry. I'll update it when conflicts are gone 💋 , thanks! 💃

**Comment by xavijam** [comment]
deployed in ded02 btw.

**Comment by rjimenezda** [comment]
Conflicts are trivial but it seems it doesn't work well with the other changes, will keep you posted.

**Comment by rjimenezda** [comment]
1c0a064 should do it 

@xavijam please test 🙇

**Comment by xavijam** [comment]
Okkkk, deploying again 💋

**Comment by xavijam** [comment]
I have to say that it works like a charm, and code for me looks legit. 

I've just found a minor thing in the histogram. When a range is selected, and you put the cursor over a selected bucket, the bin tooltip doesn't appear and it points to the first bucket (only happening in Firefox).

screen shot 2017-07-06 at 14 48 45
screen shot 2017-07-06 at 14 48 38

**Comment by rjimenezda** [comment]
For me on Firefox, if you hover over the selection range, some buckets get a tooltip 🤔

**Comment by rjimenezda** [comment]
Fixed, deploying again on ded02

**Comment by xavijam** [comment]
Working like a charm!

**Comment by xavijam** [comment]
Merging and leaving the main PR ready to be merged tomorrow 💃 .

**Pull request merged**
