### PR TITLE
Hide widgets stats by default

### PR DESCRIPTION
**Pull request by xavijam**
But if you want to show them, just set `show_stats` attribute to true.
I've found it easy to add, did I miss something? Missing any test?

screen shot 2016-02-17 at 16 37 45
---
screen shot 2016-02-17 at 16 37 50
---
screen shot 2016-02-17 at 16 37 56

CR: @viddo

### CODE REVIEW

**Comment by xavijam** [comment]
Fixes #153
Fixes #147
Fixes #146

**Comment by xavijam** [comment]
friendly ping! :dancer:

**Comment by acanimal** [comment]
@xavijam @javierarce Here https://github.com/CartoDB/deep-insights.js/pull/205 I'm i solve a couple of issues forcing to refresh the stats and buttons when widget is expanded.

More problably there will be conflicts with that two PR.

**Comment by xavijam** [comment]
I don't think so @acanimal, this only prevents to render the stats html, that's it.

**Comment by viddo** [comment]
:+1:

**Pull request merged**
