### PR TITLE
Updated examples

### LINKED ISSUE #141: Move examples, close other repo, fix local and staging machines usage.

### PR DESCRIPTION
**Pull request by xavijam**
Moved some widgets examples to this repo. Everything working properly, but **Airbnb** examples have a widget that is giving an error (rest are not affected), we should take a look.

| Title                      | Environment | CartoDB account | Working? |
|----------------------------|-------------|-----------------|----------|
| Airbnb and closest metro   | Production  | editor3         | :heavy_check_mark:       |
| Airbnb madrid October 2015 | Production  | editor3         | :heavy_check_mark:      |
| Cluster Outlier            | Production  | editor3         | :heavy_check_mark:      |
| Populated places           | Production  | editor3         | :heavy_check_mark:      |
| Namedmap                   | Staging     | pablo           | :heavy_check_mark:      |
| Time Series Widget         | Production  | editor3         | :heavy_check_mark:      |
| Torque Time Series         | Production  | editor3         | :heavy_check_mark:      |

@javisantana @saleiva @javierarce @viddo @acanimal @rochoa @fdansv 

Fixes #141

### CODE REVIEW

**Comment by xavijam** [comment]
Also namedmap example is still in staging, @alonsogarciapablo could you help me to migrate this one?

**Comment by viddo** [comment]
:ok_woman:

**Comment by saleiva** [comment]
<3

**Comment by xavijam** [comment]
Important thing, there is a new grunt task for publishing examples to gh-pages.

`grunt publish`

**Pull request merged**
