### PR TITLE
remove tags

### PR DESCRIPTION
**Pull request by piensaenpixel**
@xavijam - Related: https://github.com/CartoDB/deep-insights.js/issues/143

### CODE REVIEW

**Comment by xavijam** [comment]
:+1:

**Comment by piensaenpixel** [comment]
retest this please

**Comment by piensaenpixel** [comment]
Retest this please

**Comment by piensaenpixel** [comment]
@viddo npm install is failing i need your wisdom

**Comment by viddo** [comment]
Temporary glitch due to torque had a new release that wasn't reflected in the NPM registry. "Retest this please" doesn't work for Travis so you need to do another commit to force a run of the CI again.

**Comment by piensaenpixel** [comment]
Thanks @viddo love you

**Pull request merged**
