### PR TITLE
Underscore to hyphen

### PR DESCRIPTION
**Pull request by acanimal**
Rename files to use hyphen instead underscore.

reviewer @viddo cc @xavijam @rochoa @javierarce

### CODE REVIEW

**Comment by viddo** [comment]
> This branch has conflicts that must be resolved

:point_up: this should be fixed before merging

Also, verify that `grunt test` pass (CI is not run for PRs just yet, I'm working on fixing that as we speak).

Apart from that :+1:

**Comment by acanimal** [comment]
working, I didn't update to the last version of master

**Comment by viddo** [comment]
no merge finally?

**Comment by acanimal** [comment]
some hell when updating with master. Standardjs has punish me :)

**Pull request closed without merging**
