### PR TITLE
Extract source-map and minimize bundle on grunt build

### LINKED ISSUE #3: Implement build process to minimize JS bundles
Since the grunt tools from cartodb.js was migrated more or less "as-is" we should be able to just apply the [same grunt tasks](https://github.com/CartoDB/cartodb.js/blob/2cf4513bc6901d16f1d39dc9fdf69e9c069fd1ef/Gruntfile.js#L184-L200) in the same manner here.

### PR DESCRIPTION
**Pull request by viddo**
Resolves #3

`grunt build` will now extract source-maps and minimize (uglify) the source file so its size is reasonable to use IRL again…

@xavijam can you review? is essentially the same as in cartodb.js

### CODE REVIEW

**Comment by viddo** [comment]
retest this please

**Comment by viddo** [comment]
retest this please

**Comment by xavijam** [comment]
:+1:, what about the compressed version?

**Comment by viddo** [comment]
The compressed is generated with the changes here ofc, when doing `grunt build`

**Pull request merged**
