### PR TITLE
Category & Histogram state set/get

### PR DESCRIPTION
**Pull request by fdansv**
* [ ] Merge https://github.com/CartoDB/cartodb.js/pull/1284

@javisantana

### CODE REVIEW

**Comment by javisantana** [comment]
My main concern here is the state serialization should be done (or at least be able to do it) outside of deep-insights

In other words, the responsable of serialize state from/to url should be someone outside DI.js, for example the embed.

The reason is clear, we will want to serialize states from urls but from database as well and the current designs avoids it.

There is a simple change that improvides this a lot

```js
// var stateFromURL = URLHelper.getStateFromCurrentURL();
var stateFromURL = opts.state || URLHelper.getStateFromCurrentURL();
```
not perfect but cover that use case

There is another important thing missing, versioning. When we update widgets there will be more things, having a version will allow us to check if the state is valid. This is minor but take that into account

**Comment by fdansv** [comment]
> My main concern here is the state serialization should be done (or at least be able to do it) outside of deep-insights

Yeah that makes sense, although the scope for this feature was *dashboard state serialization*, so if we're thinking in terms of dashboards it made sense to apply it to DI.js

> There is a simple change that improvides this a lot
Ha, somewhere a few commits ago in this PR I had that precisely. Bear in mind, though, that we also have `dashboard.setState()`, which could be called from the embed, right?

**Comment by javisantana** [comment]
> Ha, somewhere a few commits ago in this PR I had that precisely. Bear in mind, though, that we also have dashboard.setState(), which could be called from the embed, right?

Yep, that's fine but is it possible to initialize the dashboard with a state?

**Comment by fdansv** [comment]
OK I see, I just added that

**Pull request merged**
