### PR TITLE
Fix shadow bars problem

### LINKED ISSUE #229: Shadow bars are not working properly

### PR DESCRIPTION
**Pull request by xavijam**
Basically I didn't take into account `originalData` for the shadow bars, and these were using the same data that the current bars have.
I've tried to not "touch" how things are right now, the main change is that `originalData` is now a `Backbone.Collection`, which provides the data to the 'shadowBars'.
If there is any *bins* change, `originalData` would be emptied and then filled with the new data.

CR: @javierarce 
Fixes #229.

### CODE REVIEW

**Comment by javierarce** [comment]
I found a problem with this branch. Whenever the mini histogram range is changed, this error appears:

```Error accessing array bounds when moving the mini histogram```

screen shot 2016-02-22 at 12 09 21

**Comment by xavijam** [comment]
Taking a look!

**Comment by xavijam** [comment]
Thanks @javierarce, already fixed! You are :top:.

**Comment by javierarce** [comment]
Great! Other than that, the code is :ok_hand:

**Comment by xavijam** [comment]
:clap:

**Pull request merged**
