### PR TITLE
Update CartoAssets to 0.1.20 

### PR DESCRIPTION
**Pull request by javierarce**
This PR also updates the CartoIcon names (removes the extra dash)

cc: @xavijam

### CODE REVIEW

**Comment by javierarce** [comment]
It seems that the package 0.1.20 is not accesible yet, and the build has failed. I'll retest it later.

**Comment by javierarce** [comment]
retest this please

**Comment by javierarce** [comment]
@xavijam: all yours.

**Comment by xavijam** [comment]
Change makes sense, have you tested it?

**Comment by xavijam** [comment]
Tested, it works like a charm \o/, dancer. :dancer:

**Pull request merged**
