### PR TITLE
Suffix and prefix attributes are not being populated 

### PR DESCRIPTION
**Pull request by xavijam**
Fixes https://github.com/CartoDB/deep-insights.js/issues/105

CR: @javierarce 

cc @viddo @alonsogarciapablo @javisantana

### CODE REVIEW

**Comment by javierarce** [comment]
:+1:

**Comment by xavijam** [comment]
Assigning it to @javisantana. We should wait until this [PR is](https://github.com/CartoDB/cartodb.js/pull/1036) merged in order to point to the last commit there in the CartoDB.js package version.

**Comment by javisantana** [comment]
@xavijam should I merge the other PR?

**Comment by xavijam** [comment]
Yes

**Comment by javisantana** [comment]
review @xavijam

**Comment by xavijam** [comment]
:+1:

**Pull request merged**
