### PR TITLE
Three points changes

### PR DESCRIPTION
**Pull request by saleiva**

### CODE REVIEW

**Comment by saleiva** [comment]
cc/ @xavijam

**Comment by xavijam** [comment]
Add the new version of the CartoAssets in the package.json please.

**Comment by xavijam** [comment]
BTW, in my opinion the HTML should be:

```html
<button class="CDB-Shape CDB-Shape-threePoints js-actions">
   <div class="CDB-Shape-threePointsItem"></div>
   <div class="CDB-Shape-threePointsItem"></div>
   <div class="CDB-Shape-threePointsItem"></div>
</button>
```
Take into account it has to be a button, where js-actions class should be included.

cc @piensaenpixel

**Comment by saleiva** [comment]
I told that to @piensaenpixel but he wanted to keep the <div> there. I leave this for you guys :)

**Comment by piensaenpixel** [comment]
@xavijam that's the way we are coding shapes in CartoAssets, for me now we can keep this way :)

**Comment by xavijam** [comment]
If the button is inside (I still don't get why) we should move the js-actions class there.

**Comment by piensaenpixel** [comment]
retest this please

**Comment by piensaenpixel** [comment]
@viddo do you know what can it happen here?

**Comment by viddo** [comment]
@piensaenpixel caching trouble on travis, should not happen again (disabled the cache for all runs in the last commit) :kissing_heart:

**Comment by piensaenpixel** [comment]
thanks @viddo, @xavijam update the package version and change the markup, take a look.

**Comment by xavijam** [comment]
Go ahead!

**Pull request merged**
