### PR TITLE
Remove ASCII 160 char from cartocss fix #10159

### PR DESCRIPTION
**Pull request by donflopez**

### CODE REVIEW

**Comment by MariaCheca** [comment]
@donflopez I was assigned to this issue 😂 But it's okay, your solution looks fine!

**Comment by donflopez** [comment]
@MariaCheca ups! I thought that I had to make the autostyling part :)

Sorry!

**Comment by xavijam** [comment]
Deep-insights is different than Builder part.

**Comment by donflopez** [comment]
Tests added @xavijam!

**Pull request merged**
