### PR TITLE
Normalize histogram

### PR DESCRIPTION
**Pull request by javisantana**
adds `normalized` option to histogram.

That means:

- the histogram height will be normalized to the data is currently showing
- the shadow bars are not shown (since they would be in different scales)

cc @xavijam

### CODE REVIEW

**Comment by xavijam** [comment]
:+1: :es:, zoomed histogram will be normalized too right?

**Comment by javisantana** [comment]
yes

**Comment by xavijam** [comment]
:us:

**Comment by xavijam** [comment]
From my point of view, all histograms should be normalized by default, as we do with categories.

**Comment by javisantana** [comment]
cc @AbelVM you have this in master :*

**Pull request merged**
