### PR TITLE
Add opts.autoStyle flag

### PR DESCRIPTION
**Pull request by donflopez**
This PR allow deactivate the autostyle button from widgets with the `autoStyle` flag passed as option to createDashboard function.

If this option is not present, the autoStyle feature is disabled by default.

### CODE REVIEW

**Comment by xavijam** [comment]
As we have talked offline, we should pass the dashboard model option `autoStyle` to each widget in order to decide if we let the button to be shown.

**Comment by xavijam** [comment]
BTW, branch in builder in order to test this -> `auto-style-feature-flag`

**Comment by donflopez** [comment]
Yep! Let's to add them!

**Comment by donflopez** [comment]
More test added @xavijam, it is ready?

**Pull request merged**
